### ISSUE TITLE
Connection problem between ROS2 in WSL2 and Unity in Windows(In ros2-for-unity, how can I define ROS DOMAIN ID ??)

### ISSUE THREAD

**Issue by Shunichi09** [RobotecAI/ros2-for-unity#103]
Hi! Thank you for your great work.

I'm trying to build a system which includes Unity in Windows11 and ROS2 in WSL2.

However,  I can not pub/sub between ROS2 in WSL2 and Unity in Windows.

I think the problem is caused by the network setting between WSL2 and Windows.
Is there anything I have to write in wslconfig??
Are there anyone who tried this setting??

I'm sorry I don't know where to write, so I decided to write this as a Issue.

Thank you for your help.

**Comment by Shunichi09** [comment]
Ok, now I understand the problem is caused by ROS DOMAIN ID.

In ros2-for-unity, how can I define ROS DOMAIN ID ??

**Comment by Shunichi09** [comment]
This solution did not work for me...
I'm using standalone Windows re-build pkg.

- https://github.com/RobotecAI/ros2-for-unity/issues/92

**Comment by adamdbrw** [comment]
Setting ROS_DOMAIN_ID on Linux will work, I have no idea about Windows or WSL2. We don't test or support WSL2 unfortunately.

**Comment by Shunichi09** [comment]
Thank you for your response!
Ok! I understand.
