### ISSUE TITLE
How to solve 'UnsatisfiedLinkError: librcl.so'?

### ISSUE THREAD

**Issue by phs4530** [RobotecAI/ros2-for-unity#109]
- Ubuntu 22.04 - Humble
- Unity 2020.3.6f1

Hello! Thank you for reading my question. 
I am planning to use ros2 using the strongalone version. However, the following error occurs. Is there a solution?
Thank you for your reply in advance

--
![image](https://github.com/RobotecAI/ros2-for-unity/assets/18480213/3bc497c1-9987-440c-a6b1-4bd3588a4dfb)
--
![image](https://github.com/RobotecAI/ros2-for-unity/assets/18480213/41bfc884-d625-45e2-a6a1-6e297e3ba223)

**Comment by omerts** [comment]
This is really a show stopper for us, if anyone can help solve this, please update

**Comment by adamdbrw** [comment]
It looks like your ROS distro is not visible. In case of standalone version, ROS libraries should be shipped with the Unity package.
Are you building from source, or using a release package?

**Comment by omerts** [comment]
@adamdbrw I used: [Ros2ForUnity_humble_standalone_ubuntu22.zip](https://github.com/RobotecAI/ros2-for-unity/releases/download/1.3.0/Ros2ForUnity_humble_standalone_ubuntu22.zip)

**Comment by adamdbrw** [comment]
Unfortunately, our support for the project is very limited at the moment, as it just works for one project we use it for and all the other projects are on Open 3D Engine, much recommended as free Unity3D alternative

**Comment by adamdbrw** [comment]
Perhaps @pijaro could help you as he prepared the build

**Comment by pijaro** [comment]
The second error may be connected to the issue (calling get_data from non-main thread).

Can you confirm, that running everything from the main thread still throws the ROS 2 error?

**Comment by phs4530** [comment]
@omerts I found it resolved in the latest branch of ros2cs.
- https://github.com/RobotecAI/ros2-for-unity/issues/78

However, the distribution version has not been updated yet.

**Comment by robotasun** [comment]
I will also add a note regarding any (standalone or overlay) install that this may occur if ROS 2 isn't sourced properly. For one of our setups this happened even though ROS was installed and sourced in the rc.

A good approach in that case is to overload your `unityhub.desktop` file to source ROS 2 before launching unityhub. Or, launching unityhub manually through your terminal. I use ZSH as my shell, so this is how it looks for me:

```
[Desktop Entry]
Name=Unity Hub
Exec=zsh -c "source /opt/ros/humble/setup.zsh && /opt/unityhub/unityhub"
Terminal=false
Type=Application
Icon=unityhub
StartupWMClass=unityhub
Comment=The Official Unity Hub
Categories=Development;
TryExec=unityhub
MimeType=x-scheme-handler/unityhub;
```
