### ISSUE TITLE
Sensor example

### ISSUE THREAD

**Issue by Simao123133** [RobotecAI/ros2-for-unity#31]
Hello,

I am trying to implement a Lidar sensor with header. I could not find an example of a sensor, only the abstract file Sensor.cs.

Best regards,
Simao

**Comment by adamdbrw** [comment]
We might share one in the future, however there is currently only the interface which you can use (or not).

You can handle the lidar in multiple ways, the simplest is probably to use RaycastCommand. Pack the data into a sensor_msgs.msg.PointCloud2 and publish it.

**Comment by adamdbrw** [comment]
Can we close this issue? @Simao123133
