### ISSUE TITLE
Had compilation error

### ISSUE THREAD

**Issue by RDaneelOlivav** [RobotecAI/ros2-for-unity#7]
Hi,

Had this issue in an Ubuntu 20, FOXY system when executing the ""**./build.sh**"" script

CMake Error at CMakeLists.txt:150 (find_package):
  By not providing "FindCycloneDDS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CycloneDDS", but CMake did not find one.

  Could not find a package configuration file provided by "CycloneDDS" with
  any of the following names:

    CycloneDDSConfig.cmake
    cyclonedds-config.cmake

  Add the installation prefix of "CycloneDDS" to CMAKE_PREFIX_PATH or set
  "CycloneDDS_DIR" to a directory containing one of the above files.  If
  "CycloneDDS" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:264 (get_standalone_dependencies)

--- stderr: ros2cs_core
CMake Error at CMakeLists.txt:150 (find_package):
  By not providing "FindCycloneDDS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CycloneDDS", but CMake did not find one.

  Could not find a package configuration file provided by "CycloneDDS" with
  any of the following names:

    CycloneDDSConfig.cmake
    cyclonedds-config.cmake

  Add the installation prefix of "CycloneDDS" to CMAKE_PREFIX_PATH or set
  "CycloneDDS_DIR" to a directory containing one of the above files.  If
  "CycloneDDS" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:264 (get_standalone_dependencies)

---
Failed   <<< ros2cs_core [0.96s, exited with code 1]

Any idea why this could happen? Any info you need extra to solve this issue just ask me and I'll be delighted to look for it :).

**Comment by adamdbrw** [comment]
This is not clear on README, added #9
