### ISSUE TITLE
On ubuntu22.04 . /build.sh --standalone is not possible

### ISSUE THREAD

**Issue by anmistu** [RobotecAI/ros2-for-unity#77]
Hello.
I am building an environment for ros2-for-unity
I'm able to do git clone and . /pull_repositories.sh, but when I try to build, I get the following error

CMake suite maintained and supported by Kitware (kitware.com/cmake).
A fatal error has occurred. The folder [/usr/share/dotnet/host/fxr] does not exist.
gmake[2]: *** [CMakeFiles/ros2cs_common.dir/build.make:82: CMakeFiles/ros2cs_common] error 131
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/ros2cs_common.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
--- stderr: ros2cs_common
A fatal error has occurred. The folder [/usr/share/dotnet/host/fxr] does not exist.
A fatal error has occurred. The folder [/usr/share/dotnet/host/fxr] does not exist.
gmake[2]: *** [CMakeFiles/ros2cs_common.dir/build.make:82: CMakeFiles/ros2cs_common] error 131
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/ros2cs_common.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

It seems that the build of ros2cs is not working, but I would like to know what to do about it. I would also like to know what to do with . /build.sh also gave the same error. Thank you in advance.

Environment: ubuntu22.04
Distribution: humble

**Comment by Muthukumar4796** [comment]
Could you please explain how you overcame the issue you were facing?
