### ISSUE TITLE
The message "Invalid message type" will appear.

### ISSUE THREAD

**Issue by anmistu** [RobotecAI/ros2-for-unity#79]
I got the following error when using ros2-for-unity to publish a custom message. Please let me know how to deal with it.

![Screenshot from 2023-07-10 18-50-18](https://github.com/RobotecAI/ros2-for-unity/assets/106851544/1d414da5-61cb-4f32-98ee-b21e8153cf7f)

publisher's source code
![image](https://github.com/RobotecAI/ros2-for-unity/assets/106851544/55307f71-56ba-4569-a3d8-25a182d48989)

custommessage file
/home/izakisyotaro/ros2_studies_ws/src/my_messages.zip

version ubuntu 22.04
distribution humble
build ./build.sh --standalone

**Comment by adamdbrw** [comment]
@izakisyoutarou this looks like you are successfully publishing your custom message, but receiving it is the problem. Did you source your custom package (my_messages) also in the terminal where you typed `ros2 topic echo`?

**Comment by anmistu** [comment]
Thanks for your reply @adamdbrw
The custom messages (my_messages) only has a cmake file, an xml file, and a message file.
So I don't think I can do ros2 topic echo because there is no topic name, how do you do it?

**Comment by adamdbrw** [comment]
You posted a screen where you ran `ros2 topic echo` command. In this console, source your built message package first. Please refer to ROS 2 resources (tutorials etc) on how to do that.

**Comment by anmistu** [comment]
I forgot the source install setup bash command. I was able to run my own message successfully. Thank you very much for your support.

**Comment by anmistu** [comment]
Sorry, you asked me to reply to this.
