### ISSUE TITLE
Issue while building ./build.sh --standalone

### ISSUE THREAD

**Issue by RajkumarIyer-StreetDrone** [RobotecAI/ros2-for-unity#97]
While trying to build ROS2forUnity I experience the following error of 
![image](https://github.com/RobotecAI/ros2-for-unity/assets/150343686/4345211d-612a-4cfa-bb94-67b86e8a1c08)
I request for assistance to solve this issue.

**Comment by Muthukumar4796** [comment]
Could you please explain how you overcame the issue you were facing?

**Comment by RajkumarIyer-StreetDrone** [comment]
I had to reinstall .net again in my system. Please follow https://learn.microsoft.com/en-us/dotnet/core/install/linux.
